### ISSUE TITLE
transcript json for certain fields(tags, speakers, etc) are represented as strings instead of an array of string

### ISSUE THREAD

**Issue by Extheoisah** [bitcointranscripts/tstbtc#104]
the json format payload we currently have is like so -> `{"speakers": "["adam jonas", "vladmir fomone"]"}`
Instead, it should be represented as -> `{"speakers": ["adam jonas", "vladmir fomone"]}`

**Comment by adamjonas** [comment]
cc SarcasticNastik

**Comment by SarcasticNastik** [comment]
I've opened up the PR; it would be nice if you verify the changes. @adamjonas @Extheoisah
