### ISSUE TITLE
feat: use gpt3 to fix the grammar and spellings in the transcript

### ISSUE THREAD

**Issue by masterchief164** [bitcointranscripts/tstbtc#90]

**Comment by adamjonas** [comment]
We don't want to correct some grammar as it doesn't reflect what was said. I'd prefer to work on a more robust post-processing solution than simply using gpt3.

**Comment by kouloumos** [comment]
The addition of this step will still not result in a finished transcript, in comparison to the transcription-review pipeline which is currently in the works; so maybe we can close this?
