### ISSUE TITLE
chore: refactoring of the codebase is needed

### ISSUE THREAD

**Issue by masterchief164** [bitcointranscripts/tstbtc#99]

**Comment by adamjonas** [comment]
Can you describe what you believe needs to be done ?

**Comment by masterchief164** [comment]
The inclusion of multiple transcribers with many options like diarization, summary creation, and topic detection has made the code a lot bloated. There are a lot of if else ladders that can be simplified. Also, the methods do not follow the SOLID principles. I'd like to address those issues and thus make the code a bit more maintanable.

**Comment by SarcasticNastik** [comment]
# Refactor Strategy 
Here, I outline a general idea for refactoring the codebase using an object-oriented approach. 

## Application Workflow

### Pre-process source files

- Given `source: Video|Audio|Yt-link`, conditionally pre-process ( _download_ and _convert_) the source files.
    - Current approach for detecting and specifying the source type and the corresponding processing is manual using `source_type`. 
Automatic detection of file type and further processing should be achieved using either:
        - Pattern matching using `match` (supported by python versions $\ge$ 10).
        - Conditional matching.

### Transcription

- Transcribe the _audio_ input to text using either deepgram or whisper.

### Post-process generated files

- Store the generated transcription from the previous section. 
- Optionally, generate a PR for the transcription.
- Optionally, upload model outputs to AWS s3.

**Comment by kouloumos** [comment]
Codebase has been refactored using an object-oriented approach into a structured four-stage process. Most of the work has been done with https://github.com/bitcointranscripts/tstbtc/pull/118 and https://github.com/bitcointranscripts/tstbtc/commit/2764a7fc273680e2ee45fa8e9fa17d7b59913574, with additional changes in miscellaneous commits that can be found in the [git history](https://github.com/bitcointranscripts/tstbtc/commits/main/).
